# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: :title
#relative_permalinks: true

# Setup
title:            Ilija Eftimov
tagline:          'A human, interested in programming'
description:      'A human, interested in programming'
url:              http://eftimov.net
baseurl:          /

author:
  name:     "Ilija Eftimov"
  github:   "fteem"
  linkedin: "ieftimov"
  twitter:  "fteem"
  email:    "ileeftimov+blog@gmail.com"
  disqus:   "eftimov"

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fteem/hyde

google_analytics: 'UA-11264459-2'

gems:
  - jekyll-paginate
